---
title: "XGBoost for Classification"
author: "Tanzeem Ahmed Nayaz"
date: "June 22, 2018"
output: html_document
---

```{r}
library(xgboost)

str(trial_smote)

```

```{r}


train_matrix <- xgb.DMatrix(data = as.matrix(trial_smote[, !(names(trial_smote) %in% c("target"))]), 
                            label = as.matrix(trial_smote[, names(trial_smote) %in% "target"]))

test_matrix <- xgb.DMatrix(data = as.matrix(test_Data))

trial_matrix <- xgb.DMatrix(data = as.matrix(train_Data[, !(names(train_Data) %in% c("target"))]), 
                            label = as.matrix(train_Data[, names(train_Data) %in% "target"]))

```

```{r}



xgb_model_basic <- xgboost(data = trial_matrix, max.depth = 2, eta = 1, nthread = 2, nround = 300, objective = "binary:logistic", verbose = 1, early_stopping_rounds = 10)


#Predict on test

prob_basic <- predict(xgb_model_basic, test_matrix)

head(prob_basic,100)

pred_basic <- ifelse(prob_basic > 0.05, 1, 0)

#Write to file

final_trial <-cbind(index,test_Data,pred_basic)

names(final_trial)[c(1,67)] = c("ID","prediction")

submission <- final_trial[,names(final_trial) %in% c("ID","prediction") ]

write.csv(submission, "C:/Users/Yunus Saleem/Desktop/Insofe/Cute-3/Submission-43-13-172056544-103644rf-193150-511649-2211238-336353-rep2458-233262-2635-423-40-2552-smote9xgbasictrain0.05.csv")

```



```{r}

library(caret)


#Standardize

std_method <- preProcess(trial_smote[, !(names(trial_smote) %in% "target")], method = c("center", "scale"))

trial_smote_reg <- predict(std_method, trial_smote)
  
test_data_reg <- predict(std_method, test_Data)

sampling_strategy <- trainControl(method = "repeatedcv", number = 5, repeats = 2, verboseIter = F, allowParallel = T)

param_grid <- expand.grid(.nrounds = 20, .max_depth = c(2, 4, 6), .eta = c(0.1, 0.3),
                          .gamma = c(0.6, 0.5, 0.3), .colsample_bytree = c(0.6, 0.4),
                          .min_child_weight = 1, .subsample = c(0.5, 0.6, 0.9))

xgb_tuned_model <- train(x = trial_smote_reg[ , !(names(trial_smote_reg) %in% c("target"))], 
                         y = trial_smote_reg[ , names(trial_smote_reg) %in% c("target")], 
                         method = "xgbTree",
                         trControl = sampling_strategy,
                         tuneGrid = param_grid)

xgb_tuned_model$bestTune

pred_basic <- predict(xgb_tuned_model, test_data_reg)


#Write to file

final_trial <-cbind(index,test_Data,pred_basic)

names(final_trial)[c(1,67)] = c("ID","prediction")

submission <- final_trial[,names(final_trial) %in% c("ID","prediction") ]

write.csv(submission, "C:/Users/Yunus Saleem/Desktop/Insofe/Cute-3/Submission-43-13-172056544-103644rf-193150-511649-2211238-336353-rep2458-233262-2635-423-40-2552-smote9xgtunetrial.csv")

```

